### ISSUE TITLE
Insulated Wire from Higher-Grade Materials

### ISSUE THREAD

**Issue by utdrmac** [egladil/oni-nubrion#13]
How come I cannot make insulated wire out of steel/tungsten? I can make conductive wire out of steel, and according to the description of insulated "By coating the wires in plastic they suddenly become much safer" implies I can make insulated wire out of all same materials as conductive, just "wrapped in plastic".

**Comment by egladil** [comment]
The insulated wire can only be made from materials with the tag Conductor, which is applied Copper, Gold, and Aluminium. These were picked because they were the only materials in the game that have an electrical resistivity of less than 3*10^−8 Ω/m (see https://en.wikipedia.org/wiki/Electrical_resistivity_and_conductivity#Resistivity_and_conductivity_of_various_materials )
Tungsten has more than twice the electrical resistivity of aluminium, and steel is about ten times worse than copper (for carbon steel, stainless steel has even higher resistivity)

**Comment by utdrmac** [comment]
Ah, very sound reasoning. Bummer, I really needed to drag an insulated wire across my rocket silo. Will have to invent alternatives then. Thanks!
